name: Pruebas Automatizadas

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Maven
        run: mvn --version

      - name: Ejecutar pruebas
        run: mvn test


      - name: Publicar Reportes de Pruebas
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reportes-pruebas
          path: target/surefire-reports/

      - name: Notificar en caso de error
        if: failure()
        run: cat target/surefire-reports/*.txt || echo "No se encontraron logs de pruebas."
